### ISSUE TITLE
容器如何开启memcached?

### ISSUE THREAD

**Issue by xiaopenggithub** [hellowzsg/docker-phper#1]
看到有memcached.sh ，如何让这个添加到容器里？

**Comment by hellowzsg** [comment]
这些*.sh文件在容器编译的时候生效。
如果你想给php安装memcached扩展，直接在.env内配置即可
![img](https://user-images.githubusercontent.com/46045921/121773262-51f93780-cbad-11eb-8903-0d09f4aaf532.png)

**Comment by xiaopenggithub** [comment]
如果想添加额外的扩展：phalcon   有参考方法吗

**Comment by hellowzsg** [comment]
@xiaopenggithub 
1. 在extensions目录下新建phalcon.sh
2. 在env中EXTENSIONS项追加,phalcon
3. phalcon.sh的内容据自身需求编写, 推荐写法如下
>  方法1(需要梯子)
> `pecl install phalcon && docker-php-ext-enable phalcon`
> 方法2
> [在这里](https://pecl.php.net/)下载相关扩展
> 将下载好的扩展放在extensions/etc/下
> 之后在phalcon.sh内写解压，编译，启用脚本(参考redis)

**Comment by xiaopenggithub** [comment]
感谢大佬耐心解答
